##
## Zsh run command configurations (for interactive shell)
##

dotfiles_folder="dotfiles"
zsh_path=$(readlink ~/.zsh)
dotfiles_path="${zsh_path%${dotfiles_folder}*}${dotfiles_folder}"
shell_path="${dotfiles_path}/shell"

if ! command -v source_files_in >/dev/null 2>&1; then
  source ${dotfiles_path}/bin/source_files_in.sh
fi

### Load shell options
if test -r ${shell_path}/options; then
  source ${shell_path}/options
fi

### Load aliases
# System aliases
if test -r ${shell_path}/aliases; then
  source ${shell_path}/aliases
fi

# App aliases
source_files_in ${dotfiles_path}/apps/**/aliases

### Load functions

# Shell functions
if test -d ${shell_path}/functions; then

  fpath+="${shell_path}/functions"
  for file in ${shell_path}/functions/*; do
    autoload $(basename $file)
  done
fi

# App functions
# TODO 
# source_files_in "${dotfiles_path}/apps/**/functions"

### Load prompt configuration
if test -r ${shell_path}/prompts; then
  source ${shell_path}/prompts
fi

### Load user defined extra configs
source_files_in "${dotfiles_path}/extra/**/*options_local"
source_files_in "${dotfiles_path}/extra/**/*zshrc*"
source_files_in "${dotfiles_path}/extra/**/*aliases*"
source_files_in "${dotfiles_path}/extra/**/*functions*"
source_files_in "${dotfiles_path}/extra/**/*prompt*"

### Removing local variables from scope
unset dotfiles_path
unset shell_path
unset zsh_path
unset dotfiles_folder
unset -f source_files_in