#!/bin/zsh
##
## Script to install your dotfiles
##
zmodload zsh/zutil || return

zparseopts -D d=dry_run -dry_run=dry_run

base_dir="$(cd "$(dirname "$0")"; pwd)"

if ! command -v print_header_footer >/dev/null 2>&1; then
  source "$base_dir/bin/print_utils.sh"
fi
  
if ! command -v install_xcode_tools >/dev/null 2>&1; then
  source "$base_dir/bin/xcode-tools.sh"
fi

if ! command -v activate_sudo >/dev/null 2>&1; then
  source "$base_dir/bin/sudo.sh"
fi

print_header_footer "Before we begin..."

if ! activate_sudo; then
  exit 1
fi

# Check for Xcode CLI availability
if ! install_xcode_tools; then
  exit 1
fi

steps=(
  "shell"
  "packages"
  "environments"
  "git"
  "ssh"
  "gpg"
  "macos"
  "apps"
)
for index in {1..$#steps}; do
  source "$base_dir/$steps[index]/install.sh" "($(($index))/$#steps)" $([[ "$dry_run" ]] && echo 1 || echo 0)
done

