#!/bin/bash
##
## Script to install your dotfiles
##

base_dir="$(cd "$(dirname "$0")"; pwd)"

if ! command -v print_header_footer >/dev/null 2>&1; then
  source "$base_dir/bin/print_utils.sh"
fi
  
if ! command -v install_xcode_tools >/dev/null 2>&1; then
  source "$base_dir/bin/xcode-tools.sh"
fi

if ! command -v activate_sudo >/dev/null 2>&1; then
  source "$base_dir/bin/sudo.sh"
fi

print_header_footer "Before we begin..."

if ! activate_sudo; then
  exit 1
fi

# Check for Xcode CLI availability
if ! install_xcode_tools; then
  exit 1
fi

steps=("shell/install.sh")
for index in ${!steps[@]}; do
  source "$base_dir/${steps[index]}" "($(($index + 1))/${#steps[@]})"
done

