#!/bin/sh
##
## Script to set Terminal's settings
##

### Terminal

# Check if there is a user-defined theme to load otherwise load "Glip Glops"
if test -n "$local_terminal_theme"; then
  terminal_theme="$local_terminal_theme"
else
  terminal_theme="Glip Glops"
fi

# Enable Secure Keyboard Entry
defaults write com.apple.terminal SecureKeyboardEntry -bool true

### View

# Hide Marks
defaults write com.apple.Terminal ShowLineMarks -int 0

### General

# On startup, set new window with profile Dracula
defaults write com.apple.terminal "Startup Window Settings" -string "$terminal_theme"

### Profiles

# Set the default window settings to Dracula
defaults write com.apple.terminal "Default Window Settings" -string "$terminal_theme"

## Advanced

# Disable Audible bell
defaults write com.apple.terminal Bell -bool false

# Enable Visual bell always
defaults write com.apple.terminal VisualBell -bool true
defaults write com.apple.terminal VisualBellOnlyWhenMuted -bool false

# Set Text encoding to UTF-8
defaults write com.apple.terminal StringEncodings -array 4

unset terminal_theme


