#!/bin/sh
##
## Script to set Dock's settings
##

# Set size of icons
defaults write com.apple.dock tilesize -float 39

# Enable magnification
defaults write com.apple.dock magnification -bool true

# Set magnificaton size
defaults write com.apple.dock largesize -float 77

# Set position
defaults write com.apple.dock orientation -string bottom 

# Set minimise effect
defaults write com.apple.dock mineffect -string genie 

# Enable minimise to icon
defaults write com.apple.dock minimize-to-application -bool true

# Enable launch animations
defaults write com.apple.dock launchanim -bool true

# Disable auto-hide
defaults write com.apple.dock autohide -bool false

# Enable launch animations
defaults write com.apple.dock show-process-indicators -bool true

# Hide recent apps
defaults write com.apple.dock show-recents -bool false

# Dock app icons

# Dock other items
