#!/bin/sh
##
## Script to set Finder's settings
##

## Appearance

# Set size

# Preferred view style to Icon
defaults write com.apple.finder FXPreferredViewStyle -string icnv

# Always Open in icon view

# Browse in icon view

# Disable stack by

# Set Sort by to Name

# Set icon size
defaults write com.apple.finder FK_StandardViewSettings-dict iconSize -float 64

# Set Grid spacing
defaults write com.apple.finder  gridSpacing -float 54

# Set text size
defaults write com.apple.finder  textSize -float 12

# Set Label position

# Disable Item Info
defaults write com.apple.finder  showItemInfo -bool false

# Enable Icon Preview
defaults write com.apple.finder  showIconPreview -bool true

# Set Background
defaults write com.apple.finder  backgroundType -int 0

# Show Sidebar
defaults write com.apple.finder ShowSidebar -bool true

# Hide Preview
defaults write com.apple.finder ShowPreviewPane -bool false

# Show Toolbar
defaults write com.apple.finder  -bool true

# Hide Tab bar
defaults write com.apple.finder ShowTabView -bool false

# Hide Path bar
defaults write com.apple.finder ShowPathbar -bool false

# Show Status bar
defaults write com.apple.finder ShowStatusBar -bool true

## General

# Show Hard Drives on Desktop
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true

# Show External Disks on Desktop
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true

# Show Removable Media on Desktop
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true

# Show Connected Servers on Desktop
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true

# New Finder window to User Home
defaults write com.apple.finder NewWindowTarget -string PfHm

# Disable Open folders in Tabs
defaults write com.apple.finder FinderSpawnTab -bool false

## Tags

## Sidebar

# Set width
defaults write com.apple.finder SidebarWidth -float 172

## Advanced

# Show all filename extensions
defaults write NSGlobalDomain AppleShowAllExtensions -bool true

# Show warning before changing extensions
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool true

# Show warning before removing from iCloud
defaults write com.apple.finder FXEnableRemoveFromICloudDriveWarning -bool true

# Show warning before emptying Bin
defaults write com.apple.finder WarnOnEmptyTrash -bool true

# Disable Remove after 30 days in Bin
defaults write com.apple.finder FXRemoveOldTrashItems -bool false

# Disable Keep folder on top while sort by name
defaults write com.apple.finder _FXSortFoldersFirst -bool false

# Enable Keep folder on top in Desktop
defaults write com.apple.finder _FXSortFoldersFirstOnDesktop -bool true

# Search in current folder
defaults write com.apple.finder FXDefaultSearchScope -string SCcf

