#!/bin/sh
##
## Script to set Transmission's settings
##

### View

# Status bar
defaults write org.m0k.transmission StatusBar -bool true

# Small view
defaults write org.m0k.transmission SmallView -bool false

# Pieces bar
defaults write org.m0k.transmission PiecesBar -bool false

# Filter bar
defaults write org.m0k.transmission FilterBar -bool true

# Availability
defaults write org.m0k.transmission DisplayProgressBarAvailable -bool false


### General

# Automatically size window to fit all transfers
defaults write org.m0k.transmission AutoSize -bool true

# Prompt user for removal of active transfers only when downloading
defaults write org.m0k.transmission CheckRemoveDownloading -bool true

# Prompt user for quit with active transfers only when downloading
defaults write org.m0k.transmission CheckQuitDownloading -bool true

# Hide the donate message
defaults write org.m0k.transmission WarningDonate -bool false

# Hide the legal disclaimer
defaults write org.m0k.transmission WarningLegal -bool false


### Transfers

# Don’t prompt for confirmation before downloading
defaults write org.m0k.transmission DownloadAsk -bool false
defaults write org.m0k.transmission MagnetOpenAsk -bool false

# Automatic Import
defaults write org.m0k.transmission AutoImport -bool true
defaults write org.m0k.transmission AutoImportDirectory -string "$HOME/Downloads/"

# Use `~/Downloads/Torrents` to store incomplete downloads
defaults write org.m0k.transmission UseIncompleteDownloadFolder -bool true
defaults write org.m0k.transmission IncompleteDownloadFolder -string "${HOME}/Downloads/.torrents"

# Use `~/Downloads` to store completed downloads
defaults write org.m0k.transmission DownloadLocationConstant -bool true
defaults write org.m0k.transmission DownloadChoice -string "Constant"
defaults write org.m0k.transmission DownloadFolder -string "${HOME}/Downloads"

# Trash original torrent files
defaults write org.m0k.transmission DeleteOriginalTorrent -bool true

# Automatic Import
defaults write org.m0k.transmission AutoImport -bool true
defaults write org.m0k.transmission AutoImportDirectory -string "$HOME/Downloads/"

# Remove seeds after ratio
defaults write org.m0k.transmission RatioCheck -bool true

# Ratio limit
defaults write org.m0k.transmission RatioLimit -bool true

# Remove inactive seeds
defaults write org.m0k.transmission IdleLimitCheck -bool true


### Bandwidth

# Upload Limit
defaults write org.m0k.transmission -int 5

# Speed Limit overrides
defaults write org.m0k.transmission SpeedLimitDownloadLimit -int 5
defaults write org.m0k.transmission SpeedLimitUploadLimit -int 5


### Peers

# Maximum connections
defaults write org.m0k.transmission PeersTotal -int 400

# Maximum connections for new transfers
defaults write org.m0k.transmission PeersTorrent -int 200

# Blocklist
defaults write org.m0k.transmission BlocklistNew -bool true

# Blocklist URL
defaults write org.m0k.transmission BlocklistURL -string "http://john.bitsurge.net/public/biglist.p2p.gz"

# Blocklist auto update
defaults write org.m0k.transmission BlocklistAutoUpdate -bool true


### Network

# Randomize port on launch
defaults write org.m0k.transmission RandomPort -bool true
